GLOBAL:
    TIMEZONE: "Europe/Prague"
    LOGFILE: "-"
    PIDFILE: "/tmp/jetconf.pid"

HTTP_SERVER:
    DOC_ROOT: "jetconf/doc-root"
    DOC_DEFAULT_NAME: "index.html"
    API_ROOT: "/restconf"
    SERVER_NAME: "hyper-h2"

    SERVER_SSL_CERT: "jetconf/server.crt"
    SERVER_SSL_PRIVKEY: "jetconf/server.key"
    CA_CERT: "jetconf/ca.pem"

NACM:
    ALLOWED_USERS: ["lojza@mail.cz"]

KNOT:
    SOCKET: "/home/pspirek/knot-conf/knot.sock"
