GLOBAL:
    TIMEZONE: "Europe/Prague"
    LOGFILE: "-"
    PIDFILE: "/tmp/jetconf.pid"
    PERSISTENT_CHANGES: true
    LOG_LEVEL: "debug"
    LOG_DBG_MODULES: ["usr_conf_data_handlers", "knot_api", "nacm"]

HTTP_SERVER:
    DOC_ROOT: "jetconf/doc-root"
    DOC_DEFAULT_NAME: "index.html"
    API_ROOT: "/restconf"
    SERVER_NAME: "hyper-h2"

    SERVER_SSL_CERT: "jetconf/server.crt"
    SERVER_SSL_PRIVKEY: "jetconf/server.key"
    CA_CERT: "jetconf/ca.pem"
    DBG_DISABLE_CERTS: false

NACM:
    ALLOWED_USERS: ["lojza@mail.cz"]

KNOT:
    SOCKET: "/home/pspirek/knot-conf/knot.sock"
